### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by eheydrick** [sensu-plugins/sensu-plugins-officehours#1]
The functionality of this mutator is basically the same as the [subdue](https://sensuapp.org/docs/latest/reference/checks.html#subdue-attributes) attribute on a check. I think we should deprecate this repo in favor of using subdue.

**Comment by majormoses** [comment]
Ya that has been around for a while, for now we should add a deprecation warning in README, repo description, and a topic. That way its very clear and then we can remove it after some time.

**Comment by eheydrick** [comment]
Added deprecation notices.
